# Generated by Django 4.1.4 on 2022-12-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_project_description_alter_project_foto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/myapp/images"
            ),
        ),
    ]
